### ISSUE TITLE
Exception on launch in Ubuntu linux 

### ISSUE THREAD

**Issue by hortiz97** [axcore/tartube#110]
I had this exception on tartube start up on Linux

is there a way to full unistall it? (can't find the package name installed)
or... is there a way to re install it?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 1988, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2241, in start
    self.load_config()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2934, in load_config
    languages=[self.custom_locale],
  File "/usr/lib/python3.6/gettext.py", line 529, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'base'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No existe el archivo o el directorio: '/var/crash/_usr_bin_tartube.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 1988, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2241, in start
    self.load_config()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2934, in load_config
    languages=[self.custom_locale],
  File "/usr/lib/python3.6/gettext.py", line 529, in translation
    raise OSError(ENOENT, 'No translation file found for domain', domain)
FileNotFoundError: [Errno 2] No translation file found for domain: 'base'
```

**Comment by axcore** [comment]
Which linux distro are you using?

**Comment by hortiz97** [comment]
I use Ubuntu 18.04 LTS all up to date... is there a way to full unnistall it, can't find the package name... Youtube-dl works well directly from the console

**Comment by axcore** [comment]
You don't say how you installed Tartube in the first place (there are several possible methods, see [here](https://github.com/axcore/tartube#installation).

Presumably you installed using the .DEB package. I have not tested uninstalling this package; probably [this link](https://askubuntu.com/questions/22200/how-to-uninstall-a-deb-package#22203) shows the correct method. If it doesn't work, then you can wait a week or two, by which time I'll have an Ubuntu installation I can test.

**Comment by hortiz97** [comment]
thanks for the support ❤️

**Comment by axcore** [comment]
I tested Tartube on Ubuntu 20.04, both installing the DEB package, and running the source code directly. I couldn't reproduce the error you reported; everything works fine.
