### ISSUE TITLE
New errors as of youtube-dl 2020.06.16.1

### ISSUE THREAD

**Issue by profucius** [axcore/tartube#112]
> Tartube 2.1
> youtube-dl 2020.06.16.1

I updated youtube-dl today, and proceeded to check/download some videos in a channel. I am receiving new errors (below).

### Issue
Errors are generated by youtube-dl when downloading a video. Below are more details.

### Settings
The only relevant settings that might be having influence over this is the General Download Options >
Formats, where I have only mp4 [size] as my list of preferred formats.

### Error
Generated by [this specific video](https://www.youtube.com/watch?v=EH-z9gE2uGY) from the channel linked above:

> [debug] Command-line args: ['--newline', '-i', '--hls-prefer-native', '-o', 'G:/Web/exurb1a/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s', '--write-thumbnail', '-f', '398+136+22+397+135+396+134+18', '--write-sub', '--embed-subs', '--download-archive', 'G:/Web/exurb1a/ytdl-archive.txt', '--verbose', 'https://www.youtube.com/watch?v=EH-z9gE2uGY']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: ()
ERROR: 'url'
Traceback (most recent call last):
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1860, in dl
    fd = get_suitable_downloader(info, self.params)(self, self.params)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/downloader/__init__.py", line 34, in get_suitable_downloader
    protocol = determine_protocol(info_dict)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/utils.py", line 4288, in determine_protocol
    url = info_dict['url']
KeyError: 'url'

**Comment by profucius** [comment]
To ensure it was not just my configuration, I completely uninstalled and reinstalled Tartube. I re-tested with a [different channel](https://www.youtube.com/channel/UC7IcJI8PUf5Z3zKxnZvTBog).

Issue # 1 happened again, some images are downloading as JPG and some as WEBP. I cannot tell why some are one and the other, it seems random at least to me. Screenshots below:

![image](https://user-images.githubusercontent.com/18254607/85139276-2cdc1e00-b212-11ea-90fe-3ded06c45120.png)
![image](https://user-images.githubusercontent.com/18254607/85139401-5c8b2600-b212-11ea-8365-8ced3818957e.png)

Issue # 2 happened again. With default settings (verbose off) I only see this error:
![image](https://user-images.githubusercontent.com/18254607/85140106-cb687f00-b212-11ea-8554-9e09162d7e93.png)

But when I turn on verbose and all other output checkboxes on (to see all information), I see the same errors as in my original post above. I'll paste these new ones below:

> [debug] Command-line args: ['--newline', '-i', '--hls-prefer-native', '-o', 'G:/Web/The School of Life/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s', '--write-thumbnail', '-f', '398+136+22+397+135+396+134+18', '--write-sub', '--embed-subs', '--download-archive', 'G:/Web/The School of Life/ytdl-archive.txt', '--verbose', 'https://www.youtube.com/watch?v=XdE17nu0zdo']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.2 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Proxy map: ()
ERROR: 'url'
Traceback (most recent call last):
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1920, in process_info
    partial_success = dl(fname, new_info)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1860, in dl
    fd = get_suitable_downloader(info, self.params)(self, self.params)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/downloader/__init__.py", line 34, in get_suitable_downloader
    protocol = determine_protocol(info_dict)
  File "D:/portablez/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/utils.py", line 4288, in determine_protocol
    url = info_dict['url']
KeyError: 'url'

**Comment by profucius** [comment]
Update: I totally uninstalled and reinstalled Tartube, and deleted my database file, while diagnosing another issue (the JPG vs WEBP one), and found that by adding only a single preferred file format (instead of multiples by priority) to the download options, the issue did not reproduce.

I will close this ticket since this resolves my issue.
