### ISSUE TITLE
Classic uses "-f mp3", which breaks youtube-dl

### ISSUE THREAD

**Issue by kurtextrem** [axcore/tartube#136]
For whatever reason I can not find, `-f mp3` is set while downloading, which breaks youtube-dl:
```
youtube-dl --newline -i --hls-prefer-native --hls-prefer-ffmpeg -o M:/Musik/%(title)s.%(ext)s --restrict-filenames -f mp3 -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata --fixup detect_or_warn --verbose https://www.youtube.com/watch?v=MoA2A1OYCXg
[youtube] MoA2A1OYCXg: Downloading webpage
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '--hls-prefer-native', '--hls-prefer-ffmpeg', '-o', 'M:/Musik/%(title)s.%(ext)s', '--restrict-filenames', '-f', 'mp3', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-thumbnail', '--add-metadata', '--fixup', 'detect_or_warn', '--verbose', 'https://www.youtube.com/watch?v=MoA2A1OYCXg']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: ()
ERROR: requested format not available
Traceback (most recent call last):
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1635, in process_video_result
    raise ExtractorError('requested format not available',
youtube_dl.utils.ExtractorError: requested format not available


```

**Comment by kurtextrem** [comment]
Never mind, I resetted settings, re-set the same settings and now it's gone. Not sure what happened.
