### ISSUE TITLE
Embedding thumbnail fails

### ISSUE THREAD

**Issue by kurtextrem** [axcore/tartube#137]
Windows 10 x64:
```
youtube-dl --newline -i -o M:/Musik/%(title)s.%(ext)s --restrict-filenames --write-thumbnail -x --audio-format mp3 --audio-quality 0 --embed-thumbnail --add-metadata --fixup detect_or_warn --verbose https://www.youtube.com/watch?v=oOPQHBkdqI8&feature=em-uploademail
[youtube] oOPQHBkdqI8: Downloading webpage
[youtube] oOPQHBkdqI8: Downloading thumbnail ...
[youtube] oOPQHBkdqI8: Writing thumbnail to: M:/Musik/Diamond_Eyes_-_23_Lyrics.webp
[debug] Invoking downloader on 'https://r8---sn-8xgn5uxa-4g5e.googlevideo.com/videoplayback?expire=1595450745&ei=GFEYX7qfPJCigQeCvoyADw&ip=92.117.133.252&id=o-APaN9SmknBYR5lCKsetmz1_52wWCoOwN3QP0J0D_erCw&itag=251&source=youtube&requiressl=yes&mh=v3&mm=31%2C29&mn=sn-8xgn5uxa-4g5e%2Csn-4g5e6nzl&ms=au%2Crdu&mv=m&mvi=8&pcm2cms=yes&pl=19&initcwndbps=1847500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4578637&dur=269.141&lmt=1595262958504468&mt=1595429073&fvip=1&keepalive=yes&fexp=23883097&c=WEB&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgP_ae6T1ZGSMZmMiEfDrx6sR3l2WR5mAIScvD57LFT9ICIQCyUafzfwdd5fuQ2Dt3MgUsXGDwuExvkFaKi1GSJCg0mQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDOXTH_R1RjUNObTZ_iySRUCv1iv7lXBhXFquJN7jEv4CIBoSuXHuDxJNIBppgLrcq5JMvyKP_j1yLHqQVCCoXDul&ratebypass=yes'
[download] Destination: M:/Musik/Diamond_Eyes_-_23_Lyrics.webm
[download] 100% of 4.37MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.webm"
[ffmpeg] Destination: M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.webm" -vn -acodec libmp3lame "-q:a" 0 "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3"
Deleting original file M:/Musik/Diamond_Eyes_-_23_Lyrics.webm (pass -k to keep)
[ffmpeg] Adding metadata to 'M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3'
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3" -c copy -metadata "title=Diamond Eyes - 23 (Lyrics)" -metadata "date=20200720" -metadata "description=Diamond Eyes - 23 (Lyrics) Airwave on Spotify: http://spoti.fi/2yL5B3I Submit your music: AirwaveMusicTV@gmail.com AirwaveMusicTV - Music for your heart.  S..." -metadata "comment=Diamond Eyes - 23 (Lyrics) Airwave on Spotify: http://spoti.fi/2yL5B3I Submit your music: AirwaveMusicTV@gmail.com AirwaveMusicTV - Music for your heart.  S..." -metadata "purl=https://www.youtube.com/watch?v=oOPQHBkdqI8" -metadata "artist=AirwaveMusicTV" "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.temp.mp3"
[ffmpeg] Adding thumbnail to "M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.mp3" -i "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.webp" -c copy -map 0 -map 1 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (Front)\"" "file:M:/Musik/Diamond_Eyes_-_23_Lyrics.temp.mp3"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '-o', 'M:/Musik/%(title)s.%(ext)s', '--restrict-filenames', '--write-thumbnail', '-x', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-thumbnail', '--add-metadata', '--fixup', 'detect_or_warn', '--verbose', 'https://www.youtube.com/watch?v=oOPQHBkdqI8&feature=em-uploademail']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3, rtmpdump 2.4
[debug] Proxy map: ()
ERROR: Conversion failed!
Traceback (most recent call last):
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/postprocessor/embedthumbnail.py", line 51, in run
    self.run_ffmpeg_multiple_files([filename, thumbnail_filename], temp_filename, options)
  File "C:/users/jacob/appdata/local/tartube/msys64/mingw64/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!
```

**Comment by kurtextrem** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/25684

**Comment by kurtextrem** [comment]
And: https://github.com/ytdl-org/youtube-dl/pull/25717

**Comment by kurtextrem** [comment]
Maybe this can be implemented in Tartube instead of waiting for youtube-dl? https://github.com/ytdl-org/youtube-dl/issues/24882

Not sure how much changes are required though.

**Comment by axcore** [comment]
I had a think about this, and I suspect there's nothing I can do. Tartube does not interact with FFmpeg and AtomicParsley _at all_; youtube-dl handles all of that.

In theory it would be possible for Tartube to override Ffmpeg handling; in practice, I think that would open a whole can of worms and I doubt I could even get it working at all.
