### ISSUE TITLE
unable to open tartube on arch

### ISSUE THREAD

**Issue by linuxgirl22** [axcore/tartube#138]
Hello :-)
I saw about TarTube when looking at the yt-dl-gui issues threads. Thank you for making this software. Unfortunately I'm having problems running it after installing it via the Aur ... running Arch (anarchy) and Mate, so am wondering if it may be a gtk2/3 problem? I'm not sure which other information could be helpful to provide, but I tried running 'tartube' in the terminal, and this was the output:

_Traceback (most recent call last):
  File "/usr/bin/tartube", line 40, in <module>
    import mainapp
  File "/usr/lib/python3.8/site-packages/tartube/mainapp.py", line 76, in <module>
    import config
  File "/usr/lib/python3.8/site-packages/tartube/config.py", line 37, in <module>
    import mainwin
  File "/usr/lib/python3.8/site-packages/tartube/mainwin.py", line 50, in <module>
    import media
  File "/usr/lib/python3.8/site-packages/tartube/media.py", line 37, in <module>
    import utils
  File "/usr/lib/python3.8/site-packages/tartube/utils.py", line 33, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'_

**Comment by axcore** [comment]
I'm not very familiar with AUR packaging, so you might get a quicker response from the [AUR maintainer](https://aur.archlinux.org/packages/tartube/). If not, I can investigate myself, but it will be some days or weeks before I can get to it.

If the AUR package doesn't work, you can install via pip or just run the source code directly - see [here](https://github.com/axcore/tartube#installation) for more information about that.

**Comment by linuxgirl22** [comment]
Thank you for your message. No problem, and will follow up on advice. Much appreciate.
