### ISSUE TITLE
pip installation not working

### ISSUE THREAD

**Issue by Yakabuff** [axcore/tartube#160]
Running linux mint 19.1. 

`Traceback (most recent call last):
  File "/usr/local/bin/tartube", line 4, in <module>
    __import__('pkg_resources').run_script('tartube==1.3.7', 'tartube')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/tartube-1.3.7-py3.6.egg/EGG-INFO/scripts/tartube", line 33, in <module>
ModuleNotFoundError: No module named 'mainapp'
`

**Comment by axcore** [comment]
Try `pip3 install tartube`

**Comment by Yakabuff** [comment]
thank you ))
