### ISSUE TITLE
deb package issue

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#164]
I successfully installed `python3-tartube_2.2.0.deb` but whenever I run `tartube` I get this error message!

```sh
$ tartube
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2192, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2343, in start
    new_config_flag = self.load_config()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3217, in load_config
    if re.search(r'avconv', self.ffmpeg_path):
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_tartube.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2192, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2343, in start
    new_config_flag = self.load_config()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3217, in load_config
    if re.search(r'avconv', self.ffmpeg_path):
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

~~**NOTE**: git clone works fine!~~
**UPDATE**: It seems git version has a similar problem
```
$ python3 tartube
Traceback (most recent call last):
  File "/home/mbnoimi/.tartube/tartube/mainapp.py", line 2192, in do_activate
    self.start()
  File "/home/mbnoimi/.tartube/tartube/mainapp.py", line 2343, in start
    new_config_flag = self.load_config()
  File "/home/mbnoimi/.tartube/tartube/mainapp.py", line 3217, in load_config
    if re.search(r'avconv', self.ffmpeg_path):
  File "/usr/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by axcore** [comment]
Fixed in v2.2.003. Git/Pypi version are uploaded already. The other installers might not be ready for a few hours.
