### ISSUE TITLE
folder -> * -> mark all as not new doesn't work

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#206]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.0

### What happens when you run Tartube from a terminal window?
this one is folder contents -> all contents -> mark as not new:

Traceback (most recent call last):
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainwin.py", line 12578, in on_video_index_mark_not_new
    self.app_obj.mark_container_new(
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 13538, in mark_container_new
    elif not flag and media_data_obj == self.fixed_fav_folder:
NameError: name 'flag' is not defined

this one is folder contents -> just folder videos -> mark as not new:
Traceback (most recent call last):
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainwin.py", line 12578, in on_video_index_mark_not_new
    self.app_obj.mark_container_new(
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 13538, in mark_container_new
    elif not flag and media_data_obj == self.fixed_fav_folder:
NameError: name 'flag' is not defined

Just let me know if you need me to download new files to test, I've been doing that between releases.

Thanks so much for making this awesome program!!

**Comment by axcore** [comment]
Thanks, fixed in v2.3.004.

If you need the updated code, you can download it from here on github, then use it to replace the code installed at **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\**

Alternatively, just wait for the next full release.

**Comment by ceonelson** [comment]
Thanks, tested and verified!
