### ISSUE TITLE
Database switching breaks db prefs window

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#209]
Thanks for taking the time to submit a bug report! Please include the following information:

I have 2 DBs for tartube. My main one is set to load by default every time.

File -> DB prefs -> choose 2nd db -> switch
then prefs window break as such:

![image](https://user-images.githubusercontent.com/16659133/101155683-16255a00-35ed-11eb-8dbc-78738b79786f.png)

but the 2nd db is loaded into the background and generates this error: 
Traceback (most recent call last):
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 14864, in on_data_dir_switch_button_clicked
    self.try_switch_db(data_dir, button2)
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 18208, in try_switch_db
    self.reset_window()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 1702, in reset_window
    self.setup_tabs()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 9287, in setup_tabs
    self.setup_options_tab()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 12867, in setup_options_tab
    self.setup_options_dl_list_tab(inner_notebook)
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 12934, in setup_options_dl_list_tab
    self.setup_options_dl_list_tab_update_treeview()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13034, in setup_options_dl_list_tab_update_treeview
    self.setup_options_dl_list_tab_add_row(
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13080, in setup_options_dl_list_tab_add_row
    media_data_obj = self.app_obj.media_reg_dict[options_obj.dbid]
KeyError: 95

I close the preferences window, then file -> db prefs but nothing shows up and this error is logged:

Traceback (most recent call last):
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 18189, in on_menu_change_db
    config.SystemPrefWin(self, 'db')
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 9112, in __init__
    self.setup()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 98, in setup
    self.setup_tabs()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 9287, in setup_tabs
    self.setup_options_tab()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 12867, in setup_options_tab
    self.setup_options_dl_list_tab(inner_notebook)
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 12934, in setup_options_dl_list_tab
    self.setup_options_dl_list_tab_update_treeview()
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13034, in setup_options_dl_list_tab_update_treeview
    self.setup_options_dl_list_tab_add_row(
  File "C:\Users\Z\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13080, in setup_options_dl_list_tab_add_row
    media_data_obj = self.app_obj.media_reg_dict[options_obj.dbid]
KeyError: 95

Thankfully I can still switch back to my main db by just closing / restarting tartube as I had that one set to always load by default :) 

I don't think this issue occurred in 2.2.060 and if it will be helpful I can restore those files and let you know.

### What operating system are you using?
Win 10

### What version of Tartube are you using?
2.3.004

**Comment by axcore** [comment]
Confirmed. Do not start Tartube until I have uploaded the fix.

**Comment by axcore** [comment]
Should be fixed in v2.3.008. I will create new releases for all formats, but you can get the updated code from git right now.

**Comment by ceonelson** [comment]
tested and confirmed, thanks!!
