### ISSUE TITLE
Can't open Preferences after failing to download one video

### ISSUE THREAD

**Issue by 1024mb** [axcore/tartube#228]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Windows 10
### What version of Tartube are you using?
2.3.008

### What happens when you run Tartube from a terminal window?
```
Traceback (most recent call last):
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 18610, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 9112, in __init__
    self.setup()
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 98, in setup
    self.setup_tabs()
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 9287, in setup_tabs
    self.setup_options_tab()
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 12867, in setup_options_tab
    self.setup_options_dl_list_tab(inner_notebook)
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 12934, in setup_options_dl_list_tab
    self.setup_options_dl_list_tab_update_treeview()
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 13034, in setup_options_dl_list_tab_update_treeview
    self.setup_options_dl_list_tab_add_row(
  File "C:\Users\angel\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 13080, in setup_options_dl_list_tab_add_row
    media_data_obj = self.app_obj.media_reg_dict[options_obj.dbid]
KeyError: 9
```

After (Failing to) download a video -I received some warning because of a bad config, I configured it to convert to mkv when it was already in mkv- I couldn't access the preferences anymore. I got that error shown above.

**Comment by axcore** [comment]
Temporary workaround: you can restore a backup copy of your database, [see here](https://github.com/axcore/tartube#76-videos-are-missing-after-a-crash).

**Comment by axcore** [comment]
I was not able to reproduce your problem exactly, but while investigating it, I found a couple of issues in the code. They may be responsible for your problem, or they may not.

There will be a full release in a couple of days, so you can either wait for that, or you can download the fixed code from github now, replacing the existing code in **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube\**. (You will need to enable hidden folders on your system first.)

**Comment by 1024mb** [comment]
> 
> 
> I was not able to reproduce your problem exactly, but while investigating it, I found a couple of issues in the code. They may be responsible for your problem, or they may not.
> 
> There will be a full release in a couple of days, so you can either wait for that, or you can download the fixed code from github now, replacing the existing code in **C:\Users\YOURNAME\AppData\Local\Tartube\msys64\home\user\tartube**. (You will need to enable hidden folders on your system first.)

Yes, it solved the issue, I can open now the settings. Thanks.

**Comment by 1024mb** [comment]
@axcore Hey, I have a question that I don't think it needs a separate issue. Here:

![python3_2020-12-24_14-29-20](https://user-images.githubusercontent.com/9301204/103104429-fe0a8e80-461e-11eb-9b28-7b8c25ec4076.png)

I can enter a numeric value but what does it refer to? KiB, MiB, GiB, TiB, PiB? Can you please make it more specific? Like adding the unit in brackets -i.e (KiB)- at the end.
