### ISSUE TITLE
missing __main__ file ?

### ISSUE THREAD

**Issue by SaudAlfurhud** [axcore/tartube#246]
i trying to install tartube on mac os 10.15.7 but when i reach final step (type: `python3 tartube/tartube`) i face this error message, **/Library/Frameworks/Python.framework/Versions/3.9/bin/python3: can't find '__main__' module in '/Users/saud/Downloads/tartube/tartube'**

**Comment by axcore** [comment]
I have never used MacOS, so there may be little I can do to help you.

However, I suspect that you are in the wrong folder. When you type `python3 tartube/tartube`, you should be in a folder containing the file `setup.py`.

Try typing the command in **/Users/saud/Downloads/tartube/** instead.

**Comment by SaudAlfurhud** [comment]
Thank you for your replay and helping me, I tried that before and also I got an error 
`Traceback (most recent call last):
  File "/Users/saud/tartube/tartube/tartube", line 40, in <module>
    import mainapp
  File "/Users/saud/tartube/tartube/mainapp.py", line 24, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'`

I should mention I preform the commant on /Users/saud/Downloads/Tartube/tartube where the setup.py file is.

**Comment by axcore** [comment]
I don't know how to help you, I'm sorry.

**Comment by SaudAlfurhud** [comment]
> Dear @SaudAlfurhud , Salam
> 
> Were you able to resolve your issue? I am stuck at the same stage Mac OS Big Sur.

I could not solve it.

**Comment by axcore** [comment]
All macOS installation problems have been consolidated into one issue, https://github.com/axcore/tartube/issues/393.
