### ISSUE TITLE
system preferences won't open

### ISSUE THREAD

**Issue by garyh1** [axcore/tartube#256]
trying to set path to youtube-dl but system preferences refuses to open. Linux mint 20

**Comment by axcore** [comment]
Please run Tartube from inside a terminal window, and tell me what error message you see.

Depending on how you installed Tartube, that probably means pressing CTRL + T, then typing `tartube`.

**Comment by garyh1** [comment]
(tartube:2572): Gdk-CRITICAL **: 06:36:31.479: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 18983, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 9235, in __init__
    self.setup()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 98, in setup
    self.setup_tabs()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 9409, in setup_tabs
    self.setup_downloader_tab()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 12591, in setup_downloader_tab
    self.setup_downloader_paths_tab(inner_notebook)
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 12847, in setup_downloader_paths_tab
    self.app_obj.ytdl_update_list.index(
ValueError: 'ytdl_update_pip3_recommend' is not in list
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_tartube.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 18983, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 9235, in __init__
    self.setup()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 98, in setup
    self.setup_tabs()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 9409, in setup_tabs
    self.setup_downloader_tab()
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 12591, in setup_downloader_tab
    self.setup_downloader_paths_tab(inner_notebook)
  File "/usr/lib/python3/dist-packages/tartube/config.py", line 12847, in setup_downloader_paths_tab
    self.app_obj.ytdl_update_list.index(
ValueError: 'ytdl_update_pip3_recommend' is not in list

**Comment by garyh1** [comment]
Re-installed everything. Working now including system preferences window

**Comment by zensubz** [comment]
Re-opening as I have this problem in CentOS 7.9 (checked with commit 7e5eb0f), and the following output is generated in the terminal when I try to invoke system-preferences:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tartube/mainapp.py", line 19452, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "/usr/lib/python3.6/site-packages/tartube/config.py", line 10277, in __init__
    self.setup()
  File "/usr/lib/python3.6/site-packages/tartube/config.py", line 104, in setup
    self.setup_tabs()
  File "/usr/lib/python3.6/site-packages/tartube/config.py", line 10451, in setup_tabs
    self.setup_downloader_tab()
  File "/usr/lib/python3.6/site-packages/tartube/config.py", line 13869, in setup_downloader_tab
    self.setup_downloader_paths_tab(inner_notebook)
  File "/usr/lib/python3.6/site-packages/tartube/config.py", line 14156, in setup_downloader_paths_tab
    self.app_obj.ytdl_update_current,
ValueError: 'ytdl_update_default_path' is not in list
```
![tartube_syspref](https://user-images.githubusercontent.com/5127872/109410079-a6412880-79bd-11eb-8ae8-cd9aa1d7289c.gif)

Would appreciate a possible fix for this issue. Thanks.

**Comment by axcore** [comment]
Can you show me the contents of Tartube's config file? (It can probably be found in  ~/.config/tartube/settings.json)

**Comment by zensubz** [comment]
I have packaged tartube (rpm) and installed it (borrowed the spec from mageia). Here are the contents of the settings.json file:

```
{
    "script_name": "tartube",
    "script_version": "2.3.097",
    "save_date": "28 Feb 2021",
    "save_time": "15:36:38",
    "file_type": "config",
    "custom_locale": "en_GB",
    "thumb_size_custom": "small",
    "main_win_save_size_flag": false,
    "main_win_save_slider_flag": false,
    "main_win_save_width": 1000,
    "main_win_save_height": 750,
    "main_win_videos_slider_posn": 250,
    "main_win_progress_slider_posn": 250,
    "main_win_classic_slider_posn": 250,
    "gtk_emulate_broken_flag": true,
    "toolbar_hide_flag": false,
    "toolbar_squeeze_flag": false,
    "show_tooltips_flag": true,
    "show_tooltips_extra_flag": true,
    "show_custom_icons_flag": false,
    "show_small_icons_in_index_flag": false,
    "auto_expand_video_index_flag": false,
    "full_expand_video_index_flag": false,
    "disable_dl_all_flag": false,
    "show_pretty_dates_flag": true,
    "catalogue_draw_frame_flag": true,
    "catalogue_draw_icons_flag": true,
    "drag_video_path_flag": true,
    "drag_video_source_flag": false,
    "drag_video_name_flag": false,
    "drag_thumb_path_flag": false,
    "show_status_icon_flag": true,
    "close_to_tray_flag": false,
    "progress_list_hide_flag": false,
    "results_list_reverse_flag": false,
    "system_error_show_flag": true,
    "system_warning_show_flag": true,
    "operation_error_show_flag": true,
    "operation_warning_show_flag": true,
    "system_msg_keep_totals_flag": false,
    "data_dir": "/home/subz/tmp/tartube-tmp",
    "data_dir_alt_list": [
        "/home/subz/tmp/tartube-tmp"
    ],
    "data_dir_use_first_flag": true,
    "data_dir_use_list_flag": true,
    "data_dir_add_from_list_flag": true,
    "sound_custom": "bell.mp3",
    "db_backup_mode": "single",
    "show_classic_tab_on_startup_flag": false,
    "classic_custom_dl_flag": false,
    "classic_dir_list": [
        "/home/subz"
    ],
    "classic_dir_previous": null,
    "classic_pending_flag": false,
    "classic_pending_list": [],
    "classic_duplicate_remove_flag": false,
    "ytdl_bin": "youtube-dl",
    "ytdl_path_default": "/usr/bin/youtube-dl",
    "ytdl_path": "/usr/bin/youtube-dl",
    "ytdl_path_custom_flag": false,
    "ytdl_update_dict": {
        "ytdl_update_disabled": []
    },
    "ytdl_update_list": [
        "ytdl_update_disabled"
    ],
    "ytdl_update_current": "ytdl_update_default_path",
    "auto_switch_output_flag": true,
    "output_size_default": 1000,
    "output_size_apply_flag": true,
    "ytdl_update_once_flag": false,
    "ytdl_fork": null,
    "ytdl_output_system_cmd_flag": true,
    "ytdl_output_stdout_flag": true,
    "ytdl_output_ignore_json_flag": true,
    "ytdl_output_ignore_progress_flag": true,
    "ytdl_output_stderr_flag": true,
    "ytdl_output_start_empty_flag": true,
    "ytdl_output_show_summary_flag": false,
    "ytdl_write_system_cmd_flag": false,
    "ytdl_write_stdout_flag": false,
    "ytdl_write_ignore_json_flag": true,
    "ytdl_write_ignore_progress_flag": true,
    "ytdl_write_stderr_flag": false,
    "ytdl_write_verbose_flag": false,
    "ytsc_write_verbose_flag": false,
    "refresh_output_videos_flag": true,
    "refresh_output_verbose_flag": false,
    "refresh_moviepy_timeout": 10,
    "disk_space_warn_flag": true,
    "disk_space_warn_limit": 1000,
    "disk_space_stop_flag": true,
    "disk_space_stop_limit": 500,
    "custom_invidious_mirror": "invidious.site",
    "custom_dl_by_video_flag": false,
    "custom_dl_divert_mode": "default",
    "custom_dl_divert_website": "",
    "custom_dl_delay_flag": false,
    "custom_dl_delay_max": 5,
    "custom_dl_delay_min": 0,
    "dl_proxy_list": [],
    "ffmpeg_path": null,
    "avconv_path": null,
    "ffmpeg_convert_webp_flag": true,
    "ytsc_path": "/usr/ytsc/youtube_stream_capture.py",
    "ytsc_priority_flag": false,
    "ytsc_wait_time": 1,
    "ytsc_restart_max": 5,
    "graph_data_type": "receive",
    "graph_plot_type": "graph",
    "graph_time_period_secs": 31536000,
    "graph_time_unit_secs": 2592000,
    "graph_ink_colour": "blue",
    "operation_limit_flag": false,
    "operation_check_limit": 3,
    "operation_download_limit": 3,
    "auto_clone_options_flag": true,
    "auto_delete_options_flag": true,
    "simple_options_flag": true,
    "enable_livestreams_flag": true,
    "livestream_max_days": 7,
    "livestream_use_colour_flag": true,
    "livestream_simple_colour_flag": false,
    "livestream_auto_notify_flag": false,
    "livestream_auto_alarm_flag": false,
    "livestream_auto_open_flag": false,
    "livestream_auto_dl_start_flag": false,
    "livestream_auto_dl_stop_flag": false,
    "scheduled_livestream_flag": true,
    "scheduled_livestream_wait_mins": 3,
    "scheduled_livestream_last_time": 0,
    "scheduled_livestream_extra_flag": true,
    "autostop_time_flag": false,
    "autostop_time_value": 1,
    "autostop_time_unit": "hours",
    "autostop_videos_flag": false,
    "autostop_videos_value": 100,
    "autostop_size_flag": false,
    "autostop_size_value": 1,
    "autostop_size_unit": "GiB",
    "operation_auto_update_flag": false,
    "operation_save_flag": true,
    "operation_sim_shortcut_flag": true,
    "operation_auto_restart_flag": false,
    "operation_auto_restart_time": 10,
    "operation_auto_restart_network_flag": false,
    "operation_auto_restart_max": 3,
    "operation_dialogue_mode": "dialogue",
    "operation_convert_mode": "channel",
    "use_module_moviepy_flag": true,
    "dialogue_copy_clipboard_flag": true,
    "dialogue_keep_open_flag": false,
    "allow_ytdl_archive_flag": true,
    "classic_ytdl_archive_flag": false,
    "apply_json_timeout_flag": true,
    "track_missing_videos_flag": false,
    "track_missing_time_flag": false,
    "track_missing_time_days": 14,
    "ignore_child_process_exit_flag": true,
    "ignore_http_404_error_flag": false,
    "ignore_data_block_error_flag": false,
    "ignore_merge_warning_flag": false,
    "ignore_missing_format_error_flag": false,
    "ignore_no_annotations_flag": true,
    "ignore_no_subtitles_flag": true,
    "ignore_yt_copyright_flag": false,
    "ignore_yt_age_restrict_flag": false,
    "ignore_yt_uploader_deleted_flag": false,
    "ignore_yt_payment_flag": false,
    "ignore_custom_msg_list": [],
    "ignore_custom_regex_flag": false,
    "num_worker_default": 2,
    "num_worker_apply_flag": true,
    "num_worker_bypass_flag": true,
    "bandwidth_default": 500,
    "bandwidth_apply_flag": false,
    "video_res_default": "720p",
    "video_res_apply_flag": false,
    "match_method": "exact_match",
    "match_first_chars": 10,
    "match_ignore_chars": 10,
    "auto_delete_flag": false,
    "auto_delete_watched_flag": false,
    "auto_delete_days": 30,
    "delete_on_shutdown_flag": false,
    "open_temp_on_desktop_flag": false,
    "complex_index_flag": false,
    "catalogue_mode": "grid_show_parent",
    "catalogue_mode_type": "grid",
    "catalogue_page_size": 50,
    "catalogue_show_filter_flag": false,
    "catalogue_sort_mode": "default",
    "catologue_use_regex_flag": false
}
```

**Comment by axcore** [comment]
Great, I have a fix for that. There will be a new release today.

**Comment by zensubz** [comment]
Thanks for the fix. I have checked with the latest git commit 7ad7221 (v2.3.110), and the system-preferences could now be accessed without any issues.
