### ISSUE TITLE
Ffmpeg error when using yt-dlp through Tartube.

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#327]
Windows 10, Tartube v2.3.332

When trying to download any video, using yt-dlp, an error occurs when yt-dlp uses ffmpeg for merging the two .webm files. This error does not occur when I use yt-dlp from the terminal.

I have appended the full output:
```yt-dlp --newline -i --hls-prefer-native --cookies E:/Tartube Storage/cookies.txt --output C:/Users/[USER]/%(title)s.%(ext)s --verbose https://youtu.be/nI-cnZRl3kY
[youtube] nI-cnZRl3kY: Downloading webpage
[youtube] nI-cnZRl3kY: Downloading android player API JSON
[info] nI-cnZRl3kY: Downloading 1 format(s): 303+251
[download] Destination: C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.f303.webm
[download] 100% of 560.35MiB in 00:29
[download] Destination: C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.f251.webm
[download] 100% of 34.25MiB in 00:01
[Merger] Merging formats into "C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.webm"
[debug] Command-line config: ['--newline', '-i', '--hls-prefer-native', '--cookies', 'E:/Tartube Storage/cookies.txt', '--output', 'C:/Users/[USER]/%(title)s.%(ext)s', '--verbose', 'https://youtu.be/nI-cnZRl3kY']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg present, ffprobe present, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: ()
[debug] [youtube] Extracting URL: https://youtu.be/nI-cnZRl3kY
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking downloader on "https://r4---sn-5hnekn7s.googlevideo.com/videoplayback?expire=1629480325&ei=JZEfYd33OoWd8gPtsqboCg&ip=185.107.95.216&id=o-ABixvn3CSRocwfwzsFoF93WnfYjJNPUdPftIqjeCZ9GJ&itag=303&source=youtube&requiressl=yes&mh=iP&mm=31%2C29&mn=sn-5hnekn7s%2Csn-5hne6nsy&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=931250&vprv=1&mime=video%2Fwebm&gir=yes&clen=587568863&dur=2206.266&lmt=1629429943177937&mt=1629458447&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6416222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPp5Pf3e2lyNc2jNGYLC3CbAy5cVBgzouHh66ClovF7rAiEAxJuImqg1m1ZuRU2KgMMeLBa6wLjDtnoj7YRlv5P8k6c%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMocPfgwxONMu4qDdXVhqucUsRZqWN-FPAcV0GPV8RjPAiEAy-CwScRzw_0GbZp-hav3QVJeG1z4opeGoxUxcu0vqlY%3D"
[debug] Invoking downloader on "https://r4---sn-5hnekn7s.googlevideo.com/videoplayback?expire=1629480325&ei=JZEfYd33OoWd8gPtsqboCg&ip=185.107.95.216&id=o-ABixvn3CSRocwfwzsFoF93WnfYjJNPUdPftIqjeCZ9GJ&itag=251&source=youtube&requiressl=yes&mh=iP&mm=31%2C29&mn=sn-5hnekn7s%2Csn-5hne6nsy&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=931250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=35918467&dur=2206.281&lmt=1629429916297508&mt=1629458447&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6411222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWA2NdJ1xNrTpGJM_Qs3Gtzktq-CWmS6vF71iOUy01k8CIA2k0cO8ahYVFbsV5ZOXwVl8JZIxb5V0y_9gBLgGNzPo&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMocPfgwxONMu4qDdXVhqucUsRZqWN-FPAcV0GPV8RjPAiEAy-CwScRzw_0GbZp-hav3QVJeG1z4opeGoxUxcu0vqlY%3D"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.f303.webm" -i "file:C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.f251.webm" -c copy -map "0:v:0" -map "1:a:0" "file:C:/Users/[USER]/Is it possible to beat Pokemon X if trainers are all LVL 100.temp.webm"
ERROR:
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/bin/yt-dlp.exe/__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/__init__.py", line 750, in main
    _real_main(argv)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/__init__.py", line 740, in _real_main
    retcode = ydl.download(all_urls)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2868, in download
    res = self.extract_info(
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1192, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2299, in process_video_result
    self.process_info(new_info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 648, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 237, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 274, in real_run_ffmpeg
    self.report_error(stderr)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 56, in report_error
    return self._downloader.report_error(text, *args, **kwargs)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 809, in report_error
    self.trouble(error_message, tb)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 765, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

ERROR: Postprocessing:
Traceback (most recent call last):
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2838, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2987, in post_process
    info = self.run_pp(pp, info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2936, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/common.py", line 83, in wrapper
    return func(self, info)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 648, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 237, in run_ffmpeg_multiple_files
    return self.real_run_ffmpeg(
  File "C:/Users/[USER]/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 275, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError
```

It's possible that this is a symptom of a different problem, but I am not sure what that may be.

**Comment by axcore** [comment]
Show me the yt-dlp command (the yellow text at the top of Tartube's Output tab), and then I can reproduce your error.

**Comment by Lux-Hue** [comment]
```yt-dlp --newline -i --hls-prefer-native --cookies E:/Tartube Storage/cookies.txt --output C:/Users/m-ess/%(title)s.%(ext)s --verbose https://youtu.be/nI-cnZRl3kY```
