### ISSUE TITLE
Unable to open system preferences

### ISSUE THREAD

**Issue by subby2006** [axcore/tartube#340]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
If using MS Windows, are you using Windows 10, Windows 7, or something else?
Windows 10

### What version of Tartube are you using?
In Tartube's main window, click Help > About
v2.3.332

### What happens when you run Tartube from a terminal window?
Many error messages are only visible in the terminal window. On MS Windows, this is how to do it:

- First, enable hidden folders on your system
- Then, run the application: 

    C:\Users\YOURNAME\AppData\Local\Tartube\msys64\mingw64.exe

- In this new window, type these commands to start Tartube:

    cd /home/user/tartube

    python3 tartube/tartube

`Traceback (most recent call last):
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 22549, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 16514, in __init__
    self.setup()
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 107, in setup
    self.setup_tabs()
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 16740, in setup_tabs
    self.setup_options_tab()
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 22032, in setup_options_tab
    self.setup_options_dl_list_tab(inner_notebook)
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 22104, in setup_options_dl_list_tab
    self.setup_options_dl_list_tab_update_treeview()
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 22211, in setup_options_dl_list_tab_update_treeview
    self.setup_options_dl_list_tab_add_row(
  File "C:/Users\Subhranil Bhattachar\AppData\Local\Tartube\msys64\home\user\tartube\tartube/config.py", line 22257, in setup_options_dl_list_tab_add_row
    media_data_obj = self.app_obj.media_reg_dict[options_obj.dbid]
KeyError: 130`

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

**Comment by Rygle** [comment]
I've had this problem on two computers, both with Windows 10. Both times I was able to access the system preferences after first having difficulty. I had only recently installed on each, and I think the thing that enables it to open later on was that it was not the first run after installation. Not sure exactly, but that was my best guess.

**Comment by axcore** [comment]
The error described in the original post suggests that download options have been assigned to a channel (or playlist or folder) which no longer exists. That probably isn't possible after a new installation.

If you feel like spending the time to test it, you could download the portable edition, and run Tartube from within a terminal window (as described [here](https://github.com/axcore/tartube#71-tartube-wont-installwont-rundoesnt-work)), which would give us an error log to read.

**Comment by axcore** [comment]
Closed for inactivity. If you have the same issue with the latest release of Tartube, please open a new issue.
