### ISSUE TITLE
Tartube Not Downloading - Outputting Python Errors

### ISSUE THREAD

**Issue by DReaper** [axcore/tartube#378]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
W10

### What version of Tartube are you using?
2.3.332. Latest version of YT-DLP. Tested developer version on GitHub, does not resolve issues.

### What happens when you run Tartube from a terminal window?
No messages in terminal window

###If your bug report is "I can't download this video", please provide a link to the video
This will save a lot of time!

Any YT link do not download. 

**Summary**
I am getting a lot of strange errors that are showing up in my Output and Error/Warnings. Nothing downloads after. Uninstalling/reinstalling does not work. However, starting a new database resolves the issue. Ideally I would not like to start a new database, but if the problem cannot be resolved, I have no choice.

**Error**
yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies T:/Youtube/cookies.txt --write-thumbnail -f bestvideo[height<=?4320][fps<=?60]+bestaudio/best[height<=?4320] --write-sub --sub-lang en --output T:/Youtube/Unsorted Videos/%(uploader)s/[%(upload_date)s] %(title)s [%(id)s] (%(resolution)s).%(ext)s https://www.youtube.com/watch?v=6hRFE1p6QmQ
Traceback (most recent call last):
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/bin/yt-dlp.exe/__main__.py", line 7, in <module>
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/__init__.py", line 857, in main
    _real_main(argv)
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/__init__.py", line 818, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 650, in __init__
    self._setup_opener()
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3682, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/cookies.py", line 86, in load_cookies
    jar.load(ignore_discard=True, ignore_expires=True)
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/site-packages/yt_dlp/utils.py", line 1607, in load
    self._really_load(cf, filename, ignore_discard, ignore_expires)
  File "C:/Users/x/AppData/Local/Tartube/msys64/mingw64/lib/python3.9/http/cookiejar.py", line 2020, in _really_load
    raise LoadError(
http.cookiejar.LoadError: 'T:/Youtube/cookies.txt' does not look like a Netscape format cookies file

**Comment by axcore** [comment]
The video you are trying to download does not exist. Test your problem with a different URL.

This appears to be a [yt-dlp](https://github.com/yt-dlp/yt-dlp) error. I checked the [yt-dlp issues page](https://github.com/yt-dlp/yt-dlp/issues) for a similar error, but did not find an obvious match.

If the cookiejar file is getting corrupted, you can tell yt-dlp not to use cookies at all. Click **Edit > General download options**. In the new window's **Name** tab there's a box for extra command line options, so just copy this into that box:

`--no-cookies ` 

The cookiejar file is stored inside the Tartube database, which explains why deleting the database also delete a corrupt cookiejar file. You could just manually delete the file yourself, or set the cookiejar file to a more convenient location, outside the database: click Edit > General download options... > Files > Cookies.

**Comment by DReaper** [comment]
Deleting the cookies and forcing it to generate a new one fixed it! It must have gotten corrupted at some point.

**Comment by axcore** [comment]
In v2.3.393 I added new download options from yt-dlp for handling cookies; see **Edit > General download options... > yt-dlp > Cookies**.
