### ISSUE TITLE
No GUI v2.3.447 on Linux Mint 20.3

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#389]
Thanks for taking the time to submit a bug report! Please include the following information:

### What operating system are you using?
Running on Linux Mint 20.3, with unofficial 5.16.15 kernel.

### What version of Tartube are you using?
Version 2.3.447.

### What happens when you run Tartube from a terminal window?
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2926, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3017, in start
    self.main_win_obj = mainwin.MainWin(self)
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 744, in __init__
    self.setup_pixbufs()
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 881, in setup_pixbufs
    self.setup_composite_pixbufs(icon_dir_path)
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 981, in setup_composite_pixbufs
    pixbuf = self.apply_pixbuf_overlay(
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 1015, in apply_pixbuf_overlay
    overlay_pixbuf = GdkPixbuf.Pixbuf.new_from_file(
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/tartube/icons/overlays/overlay_br.png”: No such file or directory (4)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_tartube.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 2926, in do_activate
    self.start()
  File "/usr/lib/python3/dist-packages/tartube/mainapp.py", line 3017, in start
    self.main_win_obj = mainwin.MainWin(self)
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 744, in __init__
    self.setup_pixbufs()
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 881, in setup_pixbufs
    self.setup_composite_pixbufs(icon_dir_path)
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 981, in setup_composite_pixbufs
    pixbuf = self.apply_pixbuf_overlay(
  File "/usr/lib/python3/dist-packages/tartube/mainwin.py", line 1015, in apply_pixbuf_overlay
    overlay_pixbuf = GdkPixbuf.Pixbuf.new_from_file(
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/share/tartube/icons/overlays/overlay_br.png”: No such file or directory (4)
```
Afterwards, there is a tartube process visible in the system monitor, but there is no GUI to interact with.
I tried uninstalling tartube, then reinstalling the latest version, but that did not help. When I revert to the previous version (v2.3.367), tartube works as expected.

By the way, I used the .deb installer that available from sourceforge to install tartube.

**Comment by pizzadude** [comment]
same in fedora 36 kde

installed via pip

had to downgrade
