### ISSUE TITLE
TypeError on show properties

### ISSUE THREAD

**Issue by ceonelson** [axcore/tartube#421]
I've been going through and dealing with all the entries that have issues with them and on some (that only have a URL set but no file associated with it) I get this error when I try to show->properties:

Traceback (most recent call last):
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/mainwin.py", line 17721, in on_video_catalogue_show_properties
    config.VideoEditWin(self.app_obj, media_data_obj)
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13846, in __init__
    self.setup()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 109, in setup
    self.setup_tabs()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 13914, in setup_tabs
    self.setup_general_tab()
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/config.py", line 14008, in setup_general_tab
    metadata_path = self.edit_obj.get_actual_path_by_ext(
  File "C:/Users\Owner\Documents\___Apps\Tartube\msys64\home\user\tartube\tartube/media.py", line 3006, in get_actual_path_by_ext
    self.file_name + ext,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by ceonelson** [comment]
I think this is probably something I can fix so I'll work on a PR for it :)

**Comment by axcore** [comment]
Fixed in v2.4.031.
