### ISSUE TITLE
system preferences bug

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#456]
```bash
Traceback (most recent call last):
  File "/home/laptop/.tartube/tartube/mainapp.py", line 24225, in on_menu_system_preferences
    config.SystemPrefWin(self)
  File "/home/laptop/.tartube/tartube/config.py", line 19265, in __init__
    self.setup()
  File "/home/laptop/.tartube/tartube/config.py", line 109, in setup
    self.setup_tabs()
  File "/home/laptop/.tartube/tartube/config.py", line 19498, in setup_tabs
    self.setup_options_tab()
  File "/home/laptop/.tartube/tartube/config.py", line 25258, in setup_options_tab
    self.setup_options_dl_list_tab(inner_notebook)
  File "/home/laptop/.tartube/tartube/config.py", line 25330, in setup_options_dl_list_tab
    self.setup_options_dl_list_tab_update_treeview()
  File "/home/laptop/.tartube/tartube/config.py", line 25437, in setup_options_dl_list_tab_update_treeview
    self.setup_options_dl_list_tab_add_row(
  File "/home/laptop/.tartube/tartube/config.py", line 25488, in setup_options_dl_list_tab_add_row
    media_data_obj = self.app_obj.media_reg_dict[options_obj.dbid]
KeyError: 71093


```
- Tartube: v2.4.093

**Comment by axcore** [comment]
What happens when you select, in the main menu, **File > Check database integrity**?

**Comment by mbnoimi** [comment]
> What happens when you select, in the main menu, **File > Check database integrity**?

There was 11 error. After fixing them I got
![image](https://user-images.githubusercontent.com/284547/192163398-459770e9-342a-4aff-bac7-4b55b695a2b4.png)

Now everything works fine. I suppose this error suppose to generate some gui error message describing what's going on.

**Comment by axcore** [comment]
Yes, something is creating holes in the database, but I don't know what.

When I have time, I will add a tracking feature, then we can discover what the problem is.

**Comment by axcore** [comment]
In v2.4.165 I added some code that auto-fixes problems like this, every time the preferences window is opened.

Also, the code responsible for assigning download options to channels/playlists/folders has been completely rewritten, so you probably won't see this error again. (But feel free to re-open the issue if you do see it again.)

**Comment by mbnoimi** [comment]
Thank you
