### ISSUE TITLE
Once again, doesn't finish!

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#485]
### What operating system are you using?
Linux Mint 21 Xfce

### What version of Tartube are you using?
- v2.4.198
- 5a0466f0215c74fc301bf4d10a2020cac98d78c5

### What happens when you run Tartube from a terminal window?
```bash
$ python tartube/tartube > ~/tartube.log
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)

(tartube:112880): Gdk-CRITICAL **: 14:02:06.481: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
/home/homeserver/.tartube/tartube/mainwin.py:4821: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  self.show_all()
/home/homeserver/.tartube/tartube/mainwin.py:4821: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  self.show_all()
/home/homeserver/.tartube/tartube/mainwin.py:4821: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  self.show_all()
/home/homeserver/.tartube/tartube/mainwin.py:4821: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  self.show_all()
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
/usr/lib/python3/dist-packages/gi/overrides/Gio.py:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/homeserver/.tartube/tartube/tartube", line 158, in handle_uncaught_exception
    raise type(value)
TypeError

Original exception was:
Traceback (most recent call last):
  File "/home/homeserver/.tartube/tartube/mainapp.py", line 21882, in dl_timer_callback
    self.main_win_obj.progress_list_display_dl_stats()
  File "/home/homeserver/.tartube/tartube/mainwin.py", line 12340, in progress_list_display_dl_stats
    and dl_stat_dict['playlist_size'] > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

(tartube:112880): Gtk-WARNING **: 15:58:38.878: infinite surface size not supported

```
`yt-dlp`  instances are finish fine
![image](https://user-images.githubusercontent.com/284547/208300666-f6a9c50c-eec3-479b-b45a-1d422121f854.png)
Tartube still saying it's downloading!

https://user-images.githubusercontent.com/284547/208300988-7361fbac-bc04-40c6-93a0-b345f3056a90.mp4

**Comment by axcore** [comment]
Fixed in v.2.4.201.

I found some problems like this one recently, but apparently I didn't find them all.
