### ISSUE TITLE
Classic download buttons disabled. Long startup AttributeError: last_sort_mode

### ISSUE THREAD

**Issue by rzechu** [axcore/tartube#498]
Long startup time, Classic mode  Download buttons disabled 
I guess its missing/broken db but have no idea which file to delete or how to fix

### What operating system are you using?
Windows 10

### What version of Tartube are you using?
2.4.221

### What happens when you run Tartube from a terminal window?
```
$ python3 tartube/tartube
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube\tartube", line 158, in
 handle_uncaught_exception
    raise type(value)
AttributeError

Original exception was:
Traceback (most recent call last):
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3306
, in do_activate
    self.start()
Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube\tartube", line 158, in handle_uncaught_exceptio
n
    raise type(value)
AttributeError

Original exception was:
Traceback (most recent call last):
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3306, in do_activate
    self.start()
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3551, in start
    self.start_continue(new_config_flag)
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 3727, in start_continue
    self.load_db()
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 6162, in load_db
    self.update_db(version)
  File "C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\tartube/mainapp.py", line 7753, in update_db
    del media_data_obj.last_sort_mode
AttributeError: last_sort_mode
```

**Comment by lsaranto** [comment]
Same in Linux (I think).

Error in sys.excepthook:
Traceback (most recent call last):
  File "tartube/tartube", line 158, in handle_uncaught_exception
    raise type(value)
AttributeError

Original exception was:
Traceback (most recent call last):
  File "/home/lasse/tartube-2.4.221/tartube/mainapp.py", line 3306, in do_activate
    self.start()
  File "/home/lasse/tartube-2.4.221/tartube/mainapp.py", line 3551, in start
    self.start_continue(new_config_flag)
  File "/home/lasse/tartube-2.4.221/tartube/mainapp.py", line 3727, in start_continue
    self.load_db()
  File "/home/lasse/tartube-2.4.221/tartube/mainapp.py", line 6162, in load_db
    self.update_db(version)
  File "/home/lasse/tartube-2.4.221/tartube/mainapp.py", line 7753, in update_db
    del media_data_obj.last_sort_mode
AttributeError: last_sort_mode

**Comment by rzechu** [comment]
> I can't reproduce this error, but I can guess what the cause is.
> 
> I uploaded a fix, if it solves your problem then I can update the main installers.
> 
> @rzechu, you can download the new source code from here on github, using it to replace the old files which you have installed in `C:/Users\admin\AppData\Local\Tartube\msys64\home\user\tartube\`

Looks it works now. Thank you!
Command line returned (but no error in tartube error tab)
```
ABC2@ABC2 MINGW64 /home/user/tartube
$ python3 tartube/tartube
C:/Users/admin/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py
:42: Warning: unable to set property 'strikethrough-set' of type 'gboolean' from value of type 'gcha
rarray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/admin/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py
:42: Warning: unable to set property 'underline-set' of type 'gboolean' from value of type 'gchararr
ay'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/admin/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py
:42: Warning: unable to set property 'weight-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)
C:/Users/admin/AppData/Local/Tartube/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/Gio.py
:42: Warning: unable to set property 'style-set' of type 'gboolean' from value of type 'gchararray'
  return Gio.Application.run(self, *args, **kwargs)


```

**Comment by axcore** [comment]
Great, those are all messages generated by bugs in the Gtk library, so no need to worry about them.
