### ISSUE TITLE
Tartube fails to launch, gives KeyError

### ISSUE THREAD

**Issue by TinaRussell** [axcore/tartube#510]
After upgrading Tartube to the latest version (2.4.245, from 2.3.110) using pip3, Tartube no longer launches; instead, I get a KeyError (more below).

### What operating system are you using?
Ubuntu MATE 22.04.2 LTS

### What version of Tartube are you using?
2.4.245, installed via pip3

### What happens when you run Tartube from a terminal window?
```
tina@pannychis:~$ tartube
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/tina/.local/bin/tartube", line 158, in handle_uncaught_exception
    raise type(value)
KeyError

Original exception was:
Traceback (most recent call last):
  File "/home/tina/.local/lib/python3.10/site-packages/tartube/mainapp.py", line 3320, in do_activate
    self.start()
  File "/home/tina/.local/lib/python3.10/site-packages/tartube/mainapp.py", line 3509, in start
    new_config_flag = self.load_config()
  File "/home/tina/.local/lib/python3.10/site-packages/tartube/mainapp.py", line 4914, in load_config
    self.check_comment_fetch_flag = json_dict['comment_fetch_flag']
KeyError: 'comment_fetch_flag'
```

I’m not sure if this is needed at all, but here’s the output from when I updated Tartube:
```
tina@pannychis:~$ pip3 install --upgrade tartube
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tartube in /usr/lib/python3/dist-packages (2.3.110)
Collecting tartube
  Downloading tartube-2.4.245-py3-none-any.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 1.8 MB/s eta 0:00:00
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (from tartube) (3.42.1)
Requirement already satisfied: feedparser in /usr/lib/python3/dist-packages (from tartube) (6.0.8)
Collecting playsound
  Downloading playsound-1.3.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib in /usr/lib/python3/dist-packages (from tartube) (3.5.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from tartube) (2.25.1)
Requirement already satisfied: pycairo>=1.16.0 in /usr/lib/python3/dist-packages (from pygobject->tartube) (1.20.1)
Building wheels for collected packages: playsound
  Building wheel for playsound (setup.py) ... done
  Created wheel for playsound: filename=playsound-1.3.0-py3-none-any.whl size=7035 sha256=56db86abeafe11cb77260aa6fc26f766068c28c7221a265316ef917ceb4aab2e
  Stored in directory: /home/tina/.cache/pip/wheels/90/89/ed/2d643f4226fc8c7c9156fc28abd8051e2d2c0de37ae51ac45c
Successfully built playsound
Installing collected packages: playsound, tartube
Successfully installed playsound-1.3.0 tartube-2.4.245
```
Let me know if you need any other information. Thank you for your efforts on this wonderful project!

**Comment by axcore** [comment]
Fixed in v2.4.255. Sorry for the inconvenience.
