### ISSUE TITLE
Tartube cannot start Ubuntu 19.10

### ISSUE THREAD

**Issue by kendoori** [axcore/tartube#57]
`kenny@pop-os:~/Downloads/tartube-master/tartube$ tartube
Gtk-Message: 15:26:09.825: Failed to load module "appmenu-gtk-module"
Missing icons directory; Tartube cannot start
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tartube-1.4.0-py3.7.egg/tartube/mainapp.py", line 1369, in do_activate
  File "/usr/local/lib/python3.7/dist-packages/tartube-1.4.0-py3.7.egg/tartube/mainapp.py", line 1459, in start
  File "/usr/local/lib/python3.7/dist-packages/tartube-1.4.0-py3.7.egg/tartube/mainwin.py", line 467, in __init__
  File "/usr/local/lib/python3.7/dist-packages/tartube-1.4.0-py3.7.egg/tartube/mainwin.py", line 611, in setup_win
  File "/usr/local/lib/python3.7/dist-packages/tartube-1.4.0-py3.7.egg/tartube/mainwin.py", line 883, in setup_main_toolbar
KeyError: 'tool_video_small'
`

**Comment by axcore** [comment]
Kendoori, if you run Tartube from the command line, you are in the wrong directory.

You must be in the directory that contains setup.py, i.e. ~/Downloads/tartube-master

Then type `python3 tartube/tartube`

**Comment by kendoori** [comment]
Thank you. That worked.

**Comment by axcore** [comment]
Don't ask me why python apps have to be structured in this way. They just do :)

**Comment by kendoori** [comment]
In case anyone sees this thread, next steps for me in the process of making this be usable were as follows:

1) Create script that executes this
`#!/bin/bash
cd /home/kenny/.tartube-master
python3 tartube/tartube`
2) Made a .desktop file pointing to the script
`#!/usr/bin/env xdg-open

[Desktop Entry]
Type=Application
Name=Tartube
Icon=/home/kenny/.tartube-master/icons/win/system_icon_512.png
Exec=/home/kenny/.bin/tartube.sh
Terminal=false
Categories=Audio;
Name[en_US]=Tartube`

**Comment by axcore** [comment]
I'm planning to add a .DEB and .RPM for the next release.
