### ISSUE TITLE
DELETE action doesn't work!

### ISSUE THREAD

**Issue by mbnoimi** [axcore/tartube#58]
Hi,

Tartube no longer usable to delete any video source (Folder/Channel/Playlist)

The generated error message:

```
Traceback (most recent call last):
  File "/home/nas/Tartube/tartube/mainwin.py", line 7240, in on_video_index_delete_container
    self.app_obj.delete_container(media_data_obj)
  File "/home/nas/Tartube/tartube/mainapp.py", line 6375, in delete_container
    empty_flag,
  File "/home/nas/Tartube/tartube/mainwin.py", line 12554, in __init__
    self.button                             # Gtk.Button
AttributeError: 'DeleteContainerDialogue' object has no attribute 'button'
```
* Tartube 1.4.0
* Commit fdbfd0211827cc81cb93baf1ff661adfabb69323

**Comment by axcore** [comment]
Fixed. Replace ../tartube/mainwin.py with the [new file](https://github.com/axcore/tartube/blob/master/tartube/mainwin.py)

(or download everything from github, using the big green button)
