### ISSUE TITLE
Can't download videos anymore

### ISSUE THREAD

**Issue by Lux-Hue** [axcore/tartube#598]
Thanks for taking the time to submit a bug report! Please include the following information:

Linux, Fedora 38
2.4.416
All youtube videos

When adding a video the the videos tab, then right-clicking and selecting "Download video", the following error pops up:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/large/.local/bin/tartube", line 158, in handle_uncaught_exception
    raise type(value)
TypeError

Original exception was:
Traceback (most recent call last):
  File "/home/large/.local/lib/python3.11/site-packages/tartube/mainwin.py", line 18052, in on_video_catalogue_dl_and_watch
    self.app_obj.download_watch_videos( [media_data_obj] )
  File "/home/large/.local/lib/python3.11/site-packages/tartube/mainapp.py", line 20263, in download_watch_videos
    self.download_manager_start('real', False, video_list)
  File "/home/large/.local/lib/python3.11/site-packages/tartube/mainapp.py", line 11342, in download_manager_start
    self.download_manager_continue([
  File "/home/large/.local/lib/python3.11/site-packages/tartube/mainapp.py", line 11476, in download_manager_continue
    or child_obj.receive_time < remove_time:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'

```

**Comment by axcore** [comment]
Fixed in v2.4.429.
