### ISSUE TITLE
FFmpegPostProcessorError, FileNotFoundError when merging

### ISSUE THREAD

**Issue by TinaRussell** [axcore/tartube#94]
I’ve been trying to download this playlist: https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa

I have my settings set to prefer mp4. But whenever I try to download this playlist (or any other, as far as I know; this is the first I’ve tried Tartube), I get the various component files (ending in `.f251.webm`, `.f398.mp4`, `.description`, `.json`, and the thumbnail `.jpg`) dumped in the destination directory, without any complete mp4 files.

Here’s the output (with debug switched on) from the beginning of the process through the end of the first video download:

```
/home/tina/.local/bin/youtube-dl --newline -i --hls-prefer-native -o /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/%(upload_date)s_%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f bestvideo[height<=?720][fps<=?60]+bestaudio/best[height<=?720] --merge-output-format mp4 --write-sub --embed-subs --add-metadata --fixup detect_or_warn --download-archive /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/ytdl-archive.txt --verbose https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa
[youtube:playlist] PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa: Downloading webpage
[download] Downloading playlist: Dr. Seuss Raps over Dr. Dre Beats
[youtube:playlist] playlist Dr. Seuss Raps over Dr. Dre Beats: Downloading 7 videos
[download] Downloading video 1 of 7
[youtube] hqIbEHNqbPs: Downloading webpage
[youtube] {18} signature length 107, html5 player c31ba6fc
[youtube] {22} signature length 103, html5 player c31ba6fc
[youtube] {137} signature length 107, html5 player c31ba6fc
[youtube] {248} signature length 103, html5 player c31ba6fc
[youtube] {399} signature length 107, html5 player c31ba6fc
[youtube] {136} signature length 107, html5 player c31ba6fc
[youtube] {247} signature length 107, html5 player c31ba6fc
[youtube] {398} signature length 103, html5 player c31ba6fc
[youtube] {135} signature length 107, html5 player c31ba6fc
[youtube] {244} signature length 107, html5 player c31ba6fc
[youtube] {397} signature length 103, html5 player c31ba6fc
[youtube] {134} signature length 107, html5 player c31ba6fc
[youtube] {243} signature length 103, html5 player c31ba6fc
[youtube] {396} signature length 107, html5 player c31ba6fc
[youtube] {133} signature length 103, html5 player c31ba6fc
[youtube] {242} signature length 107, html5 player c31ba6fc
[youtube] {395} signature length 107, html5 player c31ba6fc
[youtube] {160} signature length 107, html5 player c31ba6fc
[youtube] {278} signature length 107, html5 player c31ba6fc
[youtube] {394} signature length 107, html5 player c31ba6fc
[youtube] {140} signature length 107, html5 player c31ba6fc
[youtube] {249} signature length 107, html5 player c31ba6fc
[youtube] {250} signature length 107, html5 player c31ba6fc
[youtube] {251} signature length 107, html5 player c31ba6fc
[info] Writing video description to: /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.description
[info] Writing video description metadata as JSON to: /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.info.json
[youtube] hqIbEHNqbPs: Downloading thumbnail ...
[youtube] hqIbEHNqbPs: Writing thumbnail to: /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.jpg
[debug] Invoking downloader on 'https://r2---sn-nx5s7n7d.googlevideo.com/videoplayback?expire=1589709442&ei=IbbAXovJO5mmkgad74eQDw&ip=24.21.228.209&id=o-AP1a4zih9bdgVs2P0FWldmPZEE8Ke8NfaHZX-AIwujSM&itag=398&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&mh=AE&mm=31%2C29&mn=sn-nx5s7n7d%2Csn-nx5e6ne6&ms=au%2Crdu&mv=m&mvi=1&pl=15&initcwndbps=1812500&vprv=1&mime=video%2Fmp4&gir=yes&clen=38013725&dur=344.844&lmt=1586741553311662&mt=1589687727&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMOZOZ-4orFVNACl5LJ1g18LoiyTc4pX-5RFIvjXCnjvAiBP42YFFUDND7MLxBAMWjveg_EzftmfsWBdJ-mxYxSl7g%3D%3D&sig=AOq0QJ8wRAIgBBUzew2gDdFeBMbP-qUAd5MHb5665nE_UzxzovSRr8MCICtzpsRauzAhhEIjbsGXRGrkbazaqf6BF9nGDsTXjE0q&ratebypass=yes'
[download] Destination: /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.f398.mp4
[download] 100% of 36.25MiB in 00:03
[debug] Invoking downloader on 'https://r2---sn-nx5s7n7d.googlevideo.com/videoplayback?expire=1589709442&ei=IbbAXovJO5mmkgad74eQDw&ip=24.21.228.209&id=o-AP1a4zih9bdgVs2P0FWldmPZEE8Ke8NfaHZX-AIwujSM&itag=251&source=youtube&requiressl=yes&mh=AE&mm=31%2C29&mn=sn-nx5s7n7d%2Csn-nx5e6ne6&ms=au%2Crdu&mv=m&mvi=1&pl=15&initcwndbps=1812500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5663128&dur=344.861&lmt=1586599775925705&mt=1589687727&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMOZOZ-4orFVNACl5LJ1g18LoiyTc4pX-5RFIvjXCnjvAiBP42YFFUDND7MLxBAMWjveg_EzftmfsWBdJ-mxYxSl7g%3D%3D&sig=AOq0QJ8wRgIhAMAfnEo3lYDdZlo5n3DFeOPhUmjHh19VZlhUwbF7fnEoAiEAgxx4AnuYPmy2ondJZbgcPB7ZMGyjNucRsNr_FzhsWgg=&ratebypass=yes'
[download] Destination: /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.f251.webm
[download] 100% of 5.40MiB in 00:00
[ffmpeg] Merging formats into "/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.f398.mp4' -i 'file:/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.temp.mp4'
[ffmpeg] Adding metadata to '/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.mp4'
```
This continues, the exact same way, through the other six videos.

Here’s the beginning of the debug output for when it tries to put everything together (I mean, I guess that’s what it’s trying to do—this is the point when the debug output, at least for me, changes to light blue text):
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--newline', '-i', '--hls-prefer-native', '-o', '/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/%(upload_date)s_%(title)s.%(ext)s', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '-f', 'bestvideo[height<=?720][fps<=?60]+bestaudio/best[height<=?720]', '--merge-output-format', 'mp4', '--write-sub', '--embed-subs', '--add-metadata', '--fixup', 'detect_or_warn', '--download-archive', '/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/ytdl-archive.txt', '--verbose', 'https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2020.05.08
[debug] Python version 3.8.2 (CPython) - Linux-5.4.0-29-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: ()
WARNING: video doesn't have subtitles
WARNING: There are no annotations to write.
ERROR:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 512, in run
    self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 235, in run_ffmpeg_multiple_files
    raise FFmpegPostProcessorError(msg)
youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)

ERROR: [Errno 2] No such file or directory: '/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.mp4'
Traceback (most recent call last):
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2000, in process_info
    self.post_process(filename, info_dict)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 2065, in post_process
    files_to_delete, info = pp.run(info)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 498, in run
    self.run_ffmpeg_multiple_files(in_filenames, temp_filename, options)
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 209, in run_ffmpeg_multiple_files
    oldest_mtime = min(
  File "/home/tina/.local/lib/python3.8/site-packages/youtube_dl/postprocessor/ffmpeg.py", line 210, in <genexpr>
    os.stat(encodeFilename(path)).st_mtime for path in input_paths)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/20200328_FOX IN SOX _ Dr. Seuss Raps over Dr. Dre Beats.mp4'
```
…again, this continues in the same way for the other six videos.

I hope this is enough to figure out where the problem is. I’m using Tartube v.2.1.0 (from the deb package) on Ubuntu MATΕ 20.04. The FFmpeg package I have installed is version `7:4.2.2-1ubuntu1` from the Ubuntu repositories. Thanks!

**Comment by axcore** [comment]
Same issue as [this one](https://github.com/axcore/tartube/issues/87).

I got the same results when I download your playlist using Tartube, and when I download it using youtube-dl directly:

`youtube-dl --merge-output-format mp4 https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa`

Therefore it's a youtube-dl and/or ffmpeg issue that, at the moment, I don't know how to solve.

**Comment by axcore** [comment]
Update: I had better luck when I specified the format twice. In a terminal window, 

`youtube-dl -f mp4 --merge-output-format mp4 https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa`

In Tartube, click **Edit > General download options > Formats > Preferred**. Add mp4 as a preferred format.

Then click the **Formats > Advanced** tab, and select mp4 in the **If a merge is required after post-processing, output to this format**.

**Comment by TinaRussell** [comment]
Huh. I already had similar options in place; I had the “if merge is required” option set to mp4, and my preferred formats list consisted of (in this order): a bunch of permutations of mp4 at 720p resolution, followed by a bunch of permutations of mp4 at 720p resolution, followed by any format at 720p resolution (with and without 60fps). I didn’t have “mp4” by itself on the list, so I added it to the top (I’m assuming that the formats at the top of the list are the ones it tries first), and it didn’t seem to make a difference. But then I cleared everything but “mp4” from the list, and that did the trick, and now it seems to work just fine. (I am curious, though, if there’s still a good way to specify that I want a certain resolution if possible.)

For reference, here’s the command line used by Tartube when “mp4” was at the top of the preferred-format list, with a bunch of other stuff after it:
`/home/tina/.local/bin/youtube-dl --newline -i --hls-prefer-native -o /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/%(upload_date)s_%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f bestvideo[height<=?720][fps<=?60]+bestaudio/best[height<=?720] --merge-output-format mp4 --write-sub --embed-subs --add-metadata --fixup detect_or_warn --download-archive /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/ytdl-archive.txt --verbose https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa`

And, here’s the one it used after I cleared everything from the preferred-format list except for “mp4”:
`/home/tina/.local/bin/youtube-dl --newline -i --hls-prefer-native -o /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/%(upload_date)s_%(title)s.%(ext)s --write-description --write-info-json --write-annotations --write-thumbnail -f bestvideo[height<=?720][fps<=?60]+bestaudio/best[height<=?720] --merge-output-format mp4 --write-sub --embed-subs --add-metadata --fixup detect_or_warn --download-archive /home/tina/.local/share/tartube/Dr. Seuss Raps over Dr. Dre Beats/ytdl-archive.txt --verbose https://www.youtube.com/playlist?list=PLqvBBK0pPLrU9O6aGdGvD4ICXTGOH6FTa`

Thanks for your help!

**Comment by axcore** [comment]
Tartube v2.1.016 shows the user a warning, if they set the "if merge is required" option to mp4, and if mp4 is missing from the preferred formats list. (I think that's the best I can do, for the moment).

>I am curious, though, if there’s still a good way to specify that I want a certain resolution if possible.

You could try asking the [youtube-dl](https://github.com/ytdl-org/youtube-dl/) people. If you actually get an answer, please let me know :)
